### ISSUE TITLE
Ensure favicon works on all pages

### ISSUE THREAD

**Issue by markpundsack** [replicatedhq/troubleshoot.sh#161] opened 2020-07-09 15:35 UTC
Currently, only the marketing pages and examples have a favicon. Anything under https://troubleshoot.sh/docs/ does not.

**Comment by GraysonNull** [comment] 2020-07-09 16:37
I've been unable to reproduce this. The favicon shows on all of the pages for me. Not sure about you @jgruica

**Comment by markpundsack** [comment] 2020-07-09 16:54
@GraysonNull Weird. I'm on Chrome and can reproduce. I even opened an incognito window and reproduced. I didn't clear my cache, but I did a hard reload which is usually enough.

![image](https://user-images.githubusercontent.com/319891/87068108-b744eb80-c1da-11ea-8aff-b76401129ef8.png)

**Comment by jgruica** [comment] 2020-07-09 17:21
Yeah, I can't reproduce it too. @GraysonNull  Also, I tried different browsers. Will dig deeper into this and try to figure it out

**Comment by GraysonNull** [comment] 2020-07-09 17:40
Huh, very strange. It show the favicon for me in incognito window as well. Definitely need to dig a bit deeper to see if we can find the cause.

**Comment by markpundsack** [comment] 2020-07-09 20:28
@GraysonNull So, I'm not sure what's going on, but I see the favicon set to `/static/favicon-46c1a9ed4eb17897da46568c2442c45d.ico` on `/`, but on `/docs`, it's set to `https://troubleshoot.sh/images/favicon.ico`, which makes sense, but isn't actually a served file.

**Comment by markpundsack** [comment] 2020-07-09 20:39
Ah, market sets the icon from `import favicon from "../images/favicon.ico";` and troubleshoot theme sets it with fixed URL (`favicon: "https://troubleshoot.sh/images/favicon.ico"`), which doesn't appear to be served as an asset. At least if I hit `https://troubleshoot.sh/images/favicon.ico` right now, it just redirects. And if I `make publish`, and then look in the `public/images` directory, it's empty except for an `analyzer-icons` directory.

**Comment by jgruica** [comment] 2020-07-09 21:27
Resolved by: #166

**Closed** 2020-07-09 21:27 UTC
